services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6381:6379"
    environment:
      - TZ=Asia/Seoul
    volumes:
      - redis-data:/data

  spring-boot:
    build:
      context: .
      dockerfile: backend-spring/Dockerfile
    container_name: spring-boot
    ports:
      - "8082:8080"
    depends_on:
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=docker-prod
      - TZ=Asia/Seoul
    env_file:
      - .env

  python-ai:
    build:
      context: .
      dockerfile: backend-ai/Dockerfile
    container_name: python-ai
    ports:
      - "8002:8000"
    environment:
      - TZ=Asia/Seoul
    env_file:
      - .env
    volumes:
      - ./backend-ai/app/models:/app/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - NGINX_CONFIG=nginx-prod.conf
        - REACT_APP_API_BASE_URL=https://notimo.kro.kr/api
        - REACT_APP_AI_API_BASE_URL=https://notimo.kro.kr/ai
    container_name: frontend
    ports:
      - "3002:80"
    depends_on:
      spring-boot:
        condition: service_started
      python-ai:
        condition: service_started
    environment:
      - TZ=Asia/Seoul
    env_file:
      - ./frontend/.env.prod

volumes:
  redis-data:
