services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: notimo
    volumes:
      - mysql-data:/var/lib/mysql

  spring-boot:
    # 로컬에서는 IDE로 직접 실행할 것이므로, Docker 서비스를 비활성화합니다.
    image: alpine:latest
    container_name: spring-boot-disabled
    command: "echo 'Spring Boot is disabled in override file. Run it from your IDE.'"
    ports: [ ] # 8080번 포트 충돌 방지

  python-ai:
    build:
      context: .
      dockerfile: backend-ai/Dockerfile
    container_name: python-ai
    ports:
      - "8001:8001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}

  frontend:
    # 로컬에서는 별도 스크립트로 실행할 것이므로, Docker 서비스를 비활성화합니다.
    image: alpine:latest
    container_name: frontend-disabled
    command: "echo 'Frontend is disabled in override file. Open terminal and run: cd frontend && npm start'"
    ports: [ ] # 3000번 포트 충돌 방지

volumes:
  redis-data:
  mysql-data:
